CREATE TABLE `quality_metrics` (
	`id` text PRIMARY KEY NOT NULL,
	`timestamp` integer NOT NULL,
	`commit_hash` text NOT NULL,
	`branch` text NOT NULL,
	`lighthouse_performance` integer,
	`lighthouse_accessibility` integer,
	`lighthouse_best_practices` integer,
	`lighthouse_seo` integer,
	`lighthouse_pwa` integer,
	`lcp` integer,
	`fid` integer,
	`cls` integer,
	`test_unit_total` integer,
	`test_unit_passed` integer,
	`test_unit_failed` integer,
	`test_unit_coverage` integer,
	`test_integration_total` integer,
	`test_integration_passed` integer,
	`test_integration_failed` integer,
	`test_integration_coverage` integer,
	`test_e2e_total` integer,
	`test_e2e_passed` integer,
	`test_e2e_failed` integer,
	`test_e2e_coverage` integer,
	`bundle_size` integer,
	`load_time` integer,
	`ttfb` integer,
	`wcag_score` integer,
	`axe_violations` integer,
	`created_at` integer NOT NULL
);
